remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: [Vertikale Gärten]
description: [Dieses Projekt demonstriert, wie vertikale Gärten die Temperatur im Haus verändern und wie sie im Leben genutzt werden können.]
